/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ApiPagination } from './apiPagination';
import { GetEventResponse } from './getEventResponse';

export class GetEventsResponse {
    'pagination': ApiPagination;
    'events'?: Array<GetEventResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "ApiPagination"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<GetEventResponse>"
        }    ];

    static getAttributeTypeMap() {
        return GetEventsResponse.attributeTypeMap;
    }
}

