/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LocationLPCPayload } from './locationLPCPayload';
import { PriceArea } from './priceArea';
import { PriceCurve } from './priceCurve';
import { PriceCurvePayload } from './priceCurvePayload';
import { ResourceLPCPayload } from './resourceLPCPayload';
import { ResourceLPCTarget } from './resourceLPCTarget';
import { SparkEventPayloadType } from './sparkEventPayloadType';
import { UserEligibilityPayload } from './userEligibilityPayload';

export class GetEventResponsePayload {
    'lastUpdated'?: Date;
    'addedUsers'?: Array<string>;
    'removedUsers'?: Array<string>;
    'payloadType'?: SparkEventPayloadType;
    'targets'?: Array<ResourceLPCTarget>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "addedUsers",
            "baseName": "addedUsers",
            "type": "Array<string>"
        },
        {
            "name": "removedUsers",
            "baseName": "removedUsers",
            "type": "Array<string>"
        },
        {
            "name": "payloadType",
            "baseName": "payloadType",
            "type": "SparkEventPayloadType"
        },
        {
            "name": "targets",
            "baseName": "targets",
            "type": "Array<ResourceLPCTarget>"
        }    ];

    static getAttributeTypeMap() {
        return GetEventResponsePayload.attributeTypeMap;
    }
}

export namespace GetEventResponsePayload {
}
