/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LPCDataPoint } from './lPCDataPoint';
import { LocationTarget } from './locationTarget';

export class LPCLocationTarget {
    'location'?: LocationTarget;
    'points'?: Array<LPCDataPoint> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "location",
            "baseName": "location",
            "type": "LocationTarget"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "Array<LPCDataPoint>"
        }    ];

    static getAttributeTypeMap() {
        return LPCLocationTarget.attributeTypeMap;
    }
}

