/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EnergyCurvePoint } from './energyCurvePoint';
import { EnergyUsageReportPayload } from './energyUsageReportPayload';
import { LPCLocation } from './lPCLocation';
import { LocationEnergyUsagePlanReportPayload } from './locationEnergyUsagePlanReportPayload';
import { LocationEnergyUsageReportPayload } from './locationEnergyUsageReportPayload';
import { LocationLPCAcknowledgmentReportPayload } from './locationLPCAcknowledgmentReportPayload';
import { ResourceLPCAcknowledgmentReportPayload } from './resourceLPCAcknowledgmentReportPayload';
import { SparkReportPayloadType } from './sparkReportPayloadType';

export class PostReportRequestPayloadsInner {
    'locationId': string;
    'meterPointId': string;
    'points'?: Array<EnergyCurvePoint>;
    'resolution': string;
    'payloadType'?: SparkReportPayloadType;
    'acknowledgedTargets'?: Array<LPCLocation>;
    'declinedTargets'?: Array<LPCLocation>;
    'baseline': Array<EnergyCurvePoint>;
    'flexibility': Array<EnergyCurvePoint>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string"
        },
        {
            "name": "meterPointId",
            "baseName": "meterPointId",
            "type": "string"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "Array<EnergyCurvePoint>"
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "string"
        },
        {
            "name": "payloadType",
            "baseName": "payloadType",
            "type": "SparkReportPayloadType"
        },
        {
            "name": "acknowledgedTargets",
            "baseName": "acknowledgedTargets",
            "type": "Array<LPCLocation>"
        },
        {
            "name": "declinedTargets",
            "baseName": "declinedTargets",
            "type": "Array<LPCLocation>"
        },
        {
            "name": "baseline",
            "baseName": "baseline",
            "type": "Array<EnergyCurvePoint>"
        },
        {
            "name": "flexibility",
            "baseName": "flexibility",
            "type": "Array<EnergyCurvePoint>"
        }    ];

    static getAttributeTypeMap() {
        return PostReportRequestPayloadsInner.attributeTypeMap;
    }
}

export namespace PostReportRequestPayloadsInner {
}
