/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResourceType } from './resourceType';

export class PostLocationBoundResourceRequest {
    'resourceId'?: string;
    'resourceType'?: ResourceType;
    'meterPointId'?: string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resourceId",
            "baseName": "resourceId",
            "type": "string"
        },
        {
            "name": "resourceType",
            "baseName": "resourceType",
            "type": "ResourceType"
        },
        {
            "name": "meterPointId",
            "baseName": "meterPointId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PostLocationBoundResourceRequest.attributeTypeMap;
    }
}

export namespace PostLocationBoundResourceRequest {
}
