/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LPCLocationTarget } from './lPCLocationTarget';

export class SimulateLocationLPCEventRequest {
    'locations'?: Array<LPCLocationTarget> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "locations",
            "baseName": "locations",
            "type": "Array<LPCLocationTarget>"
        }    ];

    static getAttributeTypeMap() {
        return SimulateLocationLPCEventRequest.attributeTypeMap;
    }
}

