/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SparkEventPayload } from './sparkEventPayload';
import { SparkEventPayloadType } from './sparkEventPayloadType';

export class UserEligibilityPayload extends SparkEventPayload {
    'lastUpdated': Date;
    'addedUsers': Array<string>;
    'removedUsers': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lastUpdated",
            "baseName": "lastUpdated",
            "type": "Date"
        },
        {
            "name": "addedUsers",
            "baseName": "addedUsers",
            "type": "Array<string>"
        },
        {
            "name": "removedUsers",
            "baseName": "removedUsers",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(UserEligibilityPayload.attributeTypeMap);
    }
}

export namespace UserEligibilityPayload {
}
