/*
 * Partner webhook API
 *
 * A minimal OpenAPI spec with one POST endpoint to receive notifications from Spark energy-coordination.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Partner.Api.Converters;

namespace Partner.Api.Models
{
    /// <summary>
    /// Gets or Sets Currency
    /// </summary>

    public enum Currency
    {
        /// <summary>
        /// Enum NOK for NOK
        /// </summary>
        [EnumMember(Value = "NOK")]
        NOK = 1,

        /// <summary>
        /// Enum EUR for EUR
        /// </summary>
        [EnumMember(Value = "EUR")]
        EUR = 2,

        /// <summary>
        /// Enum SEK for SEK
        /// </summary>
        [EnumMember(Value = "SEK")]
        SEK = 3,

        /// <summary>
        /// Enum DKK for DKK
        /// </summary>
        [EnumMember(Value = "DKK")]
        DKK = 4,
    }
}
