/*
 * Partner webhook API
 *
 * A minimal OpenAPI spec with one POST endpoint to receive notifications from Spark energy-coordination.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Partner.Api.Converters;

namespace Partner.Api.Models
{
    /// <summary>
    /// Gets or Sets EnergyUnit
    /// </summary>

    public enum EnergyUnit
    {
        /// <summary>
        /// Enum KWh for kWh
        /// </summary>
        [EnumMember(Value = "kWh")]
        KWh = 1,

        /// <summary>
        /// Enum MWh for MWh
        /// </summary>
        [EnumMember(Value = "MWh")]
        MWh = 2,
    }
}
