/*
 * Partner webhook API
 *
 * A minimal OpenAPI spec with one POST endpoint to receive notifications from Spark energy-coordination.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Partner.Api.Converters;

namespace Partner.Api.Models
{
    /// <summary>
    /// Gets or Sets NotificationType
    /// </summary>

    public enum NotificationType
    {
        /// <summary>
        /// Enum Unknown for Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown,

        /// <summary>
        /// Enum PriceCurveCreated for PriceCurveCreated
        /// </summary>
        [EnumMember(Value = "PriceCurveCreated")]
        PriceCurveCreated,

        /// <summary>
        /// Enum UserEligibilityUpdated for UserEligibilityUpdated
        /// </summary>
        [EnumMember(Value = "UserEligibilityUpdated")]
        UserEligibilityUpdated,

        /// <summary>
        /// Enum LocationLPCRequested for LocationLPCRequested
        /// </summary>
        [EnumMember(Value = "LocationLPCRequested")]
        LocationLPCRequested,

        /// <summary>
        /// Enum ResourceLPCRequested for ResourceLPCRequested
        /// </summary>
        [EnumMember(Value = "ResourceLPCRequested")]
        ResourceLPCRequested,

        /// <summary>
        /// Enum LPCReservationCreated for LPCReservationCreated
        /// </summary>
        [EnumMember(Value = "LPCReservationCreated")]
        LPCReservationCreated,
    }
}
