/*
 * Partner webhook API
 *
 * A minimal OpenAPI spec with one POST endpoint to receive notifications from Spark energy-coordination.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json;
using Partner.Api.Converters;

namespace Partner.Api.Models
{
    /// <summary>
    /// Gets or Sets PriceArea
    /// </summary>

    public enum PriceArea
    {
        /// <summary>
        /// Enum Unknown for Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown,

        /// <summary>
        /// Enum NO1 for NO1
        /// </summary>
        [EnumMember(Value = "NO1")]
        NO1,

        /// <summary>
        /// Enum NO2 for NO2
        /// </summary>
        [EnumMember(Value = "NO2")]
        NO2,

        /// <summary>
        /// Enum NO3 for NO3
        /// </summary>
        [EnumMember(Value = "NO3")]
        NO3,

        /// <summary>
        /// Enum NO4 for NO4
        /// </summary>
        [EnumMember(Value = "NO4")]
        NO4,

        /// <summary>
        /// Enum NO5 for NO5
        /// </summary>
        [EnumMember(Value = "NO5")]
        NO5,

        /// <summary>
        /// Enum FI for FI
        /// </summary>
        [EnumMember(Value = "FI")]
        FI,

        /// <summary>
        /// Enum DK1 for DK1
        /// </summary>
        [EnumMember(Value = "DK1")]
        DK1,

        /// <summary>
        /// Enum DK2 for DK2
        /// </summary>
        [EnumMember(Value = "DK2")]
        DK2,

        /// <summary>
        /// Enum SE1 for SE1
        /// </summary>
        [EnumMember(Value = "SE1")]
        SE1,

        /// <summary>
        /// Enum SE2 for SE2
        /// </summary>
        [EnumMember(Value = "SE2")]
        SE2,

        /// <summary>
        /// Enum SE3 for SE3
        /// </summary>
        [EnumMember(Value = "SE3")]
        SE3,

        /// <summary>
        /// Enum SE4 for SE4
        /// </summary>
        [EnumMember(Value = "SE4")]
        SE4,
    }
}
