/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.api.auth;

import org.springframework.http.HttpHeaders;
import org.springframework.util.MultiValueMap;

@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.17.0")
public interface Authentication {
  /**
   * Apply authentication settings to header and / or query parameters.
   *
   * @param queryParams The query parameters for the request
   * @param headerParams The header parameters for the request
   * @param cookieParams The cookie parameters for the request
   */
  void applyToParams(
      MultiValueMap<String, String> queryParams,
      HttpHeaders headerParams,
      MultiValueMap<String, String> cookieParams);
}
