/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** GetEventsResponse */
@JsonPropertyOrder({
  GetEventsResponse.JSON_PROPERTY_PAGINATION,
  GetEventsResponse.JSON_PROPERTY_EVENTS
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.17.0")
public class GetEventsResponse {
  public static final String JSON_PROPERTY_PAGINATION = "pagination";
  @jakarta.annotation.Nonnull private ApiPagination pagination;

  public static final String JSON_PROPERTY_EVENTS = "events";
  @jakarta.annotation.Nullable private List<GetEventResponse> events = new ArrayList<>();

  public GetEventsResponse() {}

  public GetEventsResponse pagination(@jakarta.annotation.Nonnull ApiPagination pagination) {

    this.pagination = pagination;
    return this;
  }

  /**
   * Get pagination
   *
   * @return pagination
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ApiPagination getPagination() {
    return pagination;
  }

  @JsonProperty(value = JSON_PROPERTY_PAGINATION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPagination(@jakarta.annotation.Nonnull ApiPagination pagination) {
    this.pagination = pagination;
  }

  public GetEventsResponse events(@jakarta.annotation.Nullable List<GetEventResponse> events) {

    this.events = events;
    return this;
  }

  public GetEventsResponse addEventsItem(GetEventResponse eventsItem) {
    if (this.events == null) {
      this.events = new ArrayList<>();
    }
    this.events.add(eventsItem);
    return this;
  }

  /**
   * Get events
   *
   * @return events
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EVENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GetEventResponse> getEvents() {
    return events;
  }

  @JsonProperty(value = JSON_PROPERTY_EVENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvents(@jakarta.annotation.Nullable List<GetEventResponse> events) {
    this.events = events;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetEventsResponse getEventsResponse = (GetEventsResponse) o;
    return Objects.equals(this.pagination, getEventsResponse.pagination)
        && Objects.equals(this.events, getEventsResponse.events);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pagination, events);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetEventsResponse {\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("    events: ").append(toIndentedString(events)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
