/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

/** GetLocationResponse */
@JsonPropertyOrder({
  GetLocationResponse.JSON_PROPERTY_LOCATION_ID,
  GetLocationResponse.JSON_PROPERTY_LOCATION_TYPE,
  GetLocationResponse.JSON_PROPERTY_COORDINATES,
  GetLocationResponse.JSON_PROPERTY_METER_POINT_ID,
  GetLocationResponse.JSON_PROPERTY_METER_POINT_IDS,
  GetLocationResponse.JSON_PROPERTY_USER_ID
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.17.0")
public class GetLocationResponse {
  public static final String JSON_PROPERTY_LOCATION_ID = "locationId";
  @jakarta.annotation.Nonnull private String locationId;

  public static final String JSON_PROPERTY_LOCATION_TYPE = "locationType";
  @jakarta.annotation.Nullable private LocationType locationType;

  public static final String JSON_PROPERTY_COORDINATES = "coordinates";
  @jakarta.annotation.Nullable private Coordinate coordinates;

  public static final String JSON_PROPERTY_METER_POINT_ID = "meterPointId";

  @jakarta.annotation.Nullable
  private JsonNullable<String> meterPointId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_METER_POINT_IDS = "meterPointIds";
  @jakarta.annotation.Nullable private List<String> meterPointIds = new ArrayList<>();

  public static final String JSON_PROPERTY_USER_ID = "userId";

  @jakarta.annotation.Nullable
  private JsonNullable<String> userId = JsonNullable.<String>undefined();

  public GetLocationResponse() {}

  /** Constructor with only readonly parameters */
  @JsonCreator
  public GetLocationResponse(@JsonProperty(JSON_PROPERTY_METER_POINT_ID) String meterPointId) {
    this();
    this.meterPointId =
        meterPointId == null ? JsonNullable.<String>undefined() : JsonNullable.of(meterPointId);
  }

  public GetLocationResponse locationId(@jakarta.annotation.Nonnull String locationId) {

    this.locationId = locationId;
    return this;
  }

  /**
   * Get locationId
   *
   * @return locationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLocationId() {
    return locationId;
  }

  @JsonProperty(value = JSON_PROPERTY_LOCATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocationId(@jakarta.annotation.Nonnull String locationId) {
    this.locationId = locationId;
  }

  public GetLocationResponse locationType(@jakarta.annotation.Nullable LocationType locationType) {

    this.locationType = locationType;
    return this;
  }

  /**
   * Get locationType
   *
   * @return locationType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public LocationType getLocationType() {
    return locationType;
  }

  @JsonProperty(value = JSON_PROPERTY_LOCATION_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationType(@jakarta.annotation.Nullable LocationType locationType) {
    this.locationType = locationType;
  }

  public GetLocationResponse coordinates(@jakarta.annotation.Nullable Coordinate coordinates) {

    this.coordinates = coordinates;
    return this;
  }

  /**
   * Get coordinates
   *
   * @return coordinates
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COORDINATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Coordinate getCoordinates() {
    return coordinates;
  }

  @JsonProperty(value = JSON_PROPERTY_COORDINATES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoordinates(@jakarta.annotation.Nullable Coordinate coordinates) {
    this.coordinates = coordinates;
  }

  /**
   * Get meterPointId
   *
   * @return meterPointId
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getMeterPointId() {

    if (meterPointId == null) {
      meterPointId = JsonNullable.<String>undefined();
    }
    return meterPointId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_METER_POINT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<String> getMeterPointId_JsonNullable() {
    return meterPointId;
  }

  @JsonProperty(JSON_PROPERTY_METER_POINT_ID)
  private void setMeterPointId_JsonNullable(JsonNullable<String> meterPointId) {
    this.meterPointId = meterPointId;
  }

  public GetLocationResponse meterPointIds(
      @jakarta.annotation.Nullable List<String> meterPointIds) {

    this.meterPointIds = meterPointIds;
    return this;
  }

  public GetLocationResponse addMeterPointIdsItem(String meterPointIdsItem) {
    if (this.meterPointIds == null) {
      this.meterPointIds = new ArrayList<>();
    }
    this.meterPointIds.add(meterPointIdsItem);
    return this;
  }

  /**
   * Get meterPointIds
   *
   * @return meterPointIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METER_POINT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getMeterPointIds() {
    return meterPointIds;
  }

  @JsonProperty(value = JSON_PROPERTY_METER_POINT_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeterPointIds(@jakarta.annotation.Nullable List<String> meterPointIds) {
    this.meterPointIds = meterPointIds;
  }

  public GetLocationResponse userId(@jakarta.annotation.Nullable String userId) {
    this.userId = JsonNullable.<String>of(userId);

    return this;
  }

  /**
   * Get userId
   *
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getUserId() {
    return userId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<String> getUserId_JsonNullable() {
    return userId;
  }

  @JsonProperty(JSON_PROPERTY_USER_ID)
  public void setUserId_JsonNullable(JsonNullable<String> userId) {
    this.userId = userId;
  }

  public void setUserId(@jakarta.annotation.Nullable String userId) {
    this.userId = JsonNullable.<String>of(userId);
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetLocationResponse getLocationResponse = (GetLocationResponse) o;
    return Objects.equals(this.locationId, getLocationResponse.locationId)
        && Objects.equals(this.locationType, getLocationResponse.locationType)
        && Objects.equals(this.coordinates, getLocationResponse.coordinates)
        && equalsNullable(this.meterPointId, getLocationResponse.meterPointId)
        && Objects.equals(this.meterPointIds, getLocationResponse.meterPointIds)
        && equalsNullable(this.userId, getLocationResponse.userId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b
        || (a != null
            && b != null
            && a.isPresent()
            && b.isPresent()
            && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        locationId,
        locationType,
        coordinates,
        hashCodeNullable(meterPointId),
        meterPointIds,
        hashCodeNullable(userId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetLocationResponse {\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    locationType: ").append(toIndentedString(locationType)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    meterPointId: ").append(toIndentedString(meterPointId)).append("\n");
    sb.append("    meterPointIds: ").append(toIndentedString(meterPointIds)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
