/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/** GetUserEligibilityResponse */
@JsonPropertyOrder({
  GetUserEligibilityResponse.JSON_PROPERTY_USER_ID,
  GetUserEligibilityResponse.JSON_PROPERTY_IS_ELIGIBLE
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.9.0-SNAPSHOT")
public class GetUserEligibilityResponse {
  public static final String JSON_PROPERTY_USER_ID = "userId";
  private String userId;

  public static final String JSON_PROPERTY_IS_ELIGIBLE = "isEligible";
  private Boolean isEligible;

  public GetUserEligibilityResponse() {}

  public GetUserEligibilityResponse userId(String userId) {

    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   *
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUserId() {
    return userId;
  }

  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(String userId) {
    this.userId = userId;
  }

  public GetUserEligibilityResponse isEligible(Boolean isEligible) {

    this.isEligible = isEligible;
    return this;
  }

  /**
   * Get isEligible
   *
   * @return isEligible
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_ELIGIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsEligible() {
    return isEligible;
  }

  @JsonProperty(JSON_PROPERTY_IS_ELIGIBLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEligible(Boolean isEligible) {
    this.isEligible = isEligible;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetUserEligibilityResponse getUserEligibilityResponse = (GetUserEligibilityResponse) o;
    return Objects.equals(this.userId, getUserEligibilityResponse.userId)
        && Objects.equals(this.isEligible, getUserEligibilityResponse.isEligible);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, isEligible);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetUserEligibilityResponse {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    isEligible: ").append(toIndentedString(isEligible)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
