/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

/** PostReportRequestPayloadsInner */
@JsonPropertyOrder({
  PostReportRequestPayloadsInner.JSON_PROPERTY_PAYLOAD_TYPE,
  PostReportRequestPayloadsInner.JSON_PROPERTY_RESOURCE_ID,
  PostReportRequestPayloadsInner.JSON_PROPERTY_LOCATION_ID,
  PostReportRequestPayloadsInner.JSON_PROPERTY_METER_POINT_ID,
  PostReportRequestPayloadsInner.JSON_PROPERTY_POINTS,
  PostReportRequestPayloadsInner.JSON_PROPERTY_RESOLUTION,
  PostReportRequestPayloadsInner.JSON_PROPERTY_CURVE_POINTS,
  PostReportRequestPayloadsInner.JSON_PROPERTY_ACKNOWLEDGED_TARGETS,
  PostReportRequestPayloadsInner.JSON_PROPERTY_DECLINED_TARGETS,
  PostReportRequestPayloadsInner.JSON_PROPERTY_BASELINE,
  PostReportRequestPayloadsInner.JSON_PROPERTY_FLEXIBILITY
})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.17.0")
@JsonIgnoreProperties(
    value =
        "payloadType", // ignore manually set payloadType, it will be automatically generated by
                       // Jackson during serialization
    allowSetters = true // allows the payloadType to be set during deserialization
    )
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "payloadType",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = EnergyUsageReportPayload.class, name = "EnergyUsage"),
  @JsonSubTypes.Type(value = LocationEnergyUsageReportPayload.class, name = "LocationEnergyUsage"),
  @JsonSubTypes.Type(
      value = LocationEnergyUsagePlanReportPayload.class,
      name = "LocationEnergyUsagePlan"),
  @JsonSubTypes.Type(
      value = LocationLPCAcknowledgmentReportPayload.class,
      name = "LocationLPCAcknowledgement"),
  @JsonSubTypes.Type(
      value = ResourceLPCAcknowledgmentReportPayload.class,
      name = "ResourceLPCAcknowledgement"),
})
public class PostReportRequestPayloadsInner {
  public static final String JSON_PROPERTY_PAYLOAD_TYPE = "payloadType";
  // The discriminator does not have Nullability-annotation since it is added during serialization
  // by the @JsonTypeName annotation
  private SparkReportPayloadType payloadType;

  public static final String JSON_PROPERTY_RESOURCE_ID = "resourceId";
  @jakarta.annotation.Nonnull private String resourceId;

  public static final String JSON_PROPERTY_LOCATION_ID = "locationId";
  @jakarta.annotation.Nonnull private String locationId;

  public static final String JSON_PROPERTY_METER_POINT_ID = "meterPointId";
  @jakarta.annotation.Nonnull private String meterPointId;

  public static final String JSON_PROPERTY_POINTS = "points";
  @jakarta.annotation.Nullable private List<EnergyCurvePoint> points = new ArrayList<>();

  public static final String JSON_PROPERTY_RESOLUTION = "resolution";
  @jakarta.annotation.Nonnull private String resolution;

  public static final String JSON_PROPERTY_CURVE_POINTS = "curvePoints";

  @jakarta.annotation.Nullable
  private JsonNullable<List<EnergyCurvePoint>> curvePoints =
      JsonNullable.<List<EnergyCurvePoint>>undefined();

  public static final String JSON_PROPERTY_ACKNOWLEDGED_TARGETS = "acknowledgedTargets";
  @jakarta.annotation.Nullable private List<LPCLocation> acknowledgedTargets = new ArrayList<>();

  public static final String JSON_PROPERTY_DECLINED_TARGETS = "declinedTargets";
  @jakarta.annotation.Nullable private List<LPCLocation> declinedTargets = new ArrayList<>();

  public static final String JSON_PROPERTY_BASELINE = "baseline";
  @jakarta.annotation.Nonnull private List<EnergyCurvePoint> baseline = new ArrayList<>();

  public static final String JSON_PROPERTY_FLEXIBILITY = "flexibility";
  @jakarta.annotation.Nonnull private List<EnergyCurvePoint> flexibility = new ArrayList<>();

  public PostReportRequestPayloadsInner() {}

  public PostReportRequestPayloadsInner payloadType(
      @jakarta.annotation.Nullable SparkReportPayloadType payloadType) {

    this.payloadType = payloadType;
    return this;
  }

  /**
   * Get payloadType
   *
   * @return payloadType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public SparkReportPayloadType getPayloadType() {
    return payloadType;
  }

  @JsonProperty(value = JSON_PROPERTY_PAYLOAD_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPayloadType(@jakarta.annotation.Nullable SparkReportPayloadType payloadType) {
    this.payloadType = payloadType;
  }

  public PostReportRequestPayloadsInner resourceId(@jakarta.annotation.Nonnull String resourceId) {

    this.resourceId = resourceId;
    return this;
  }

  /**
   * Get resourceId
   *
   * @return resourceId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESOURCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResourceId() {
    return resourceId;
  }

  @JsonProperty(value = JSON_PROPERTY_RESOURCE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResourceId(@jakarta.annotation.Nonnull String resourceId) {
    this.resourceId = resourceId;
  }

  public PostReportRequestPayloadsInner locationId(@jakarta.annotation.Nonnull String locationId) {

    this.locationId = locationId;
    return this;
  }

  /**
   * Get locationId
   *
   * @return locationId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LOCATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLocationId() {
    return locationId;
  }

  @JsonProperty(value = JSON_PROPERTY_LOCATION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLocationId(@jakarta.annotation.Nonnull String locationId) {
    this.locationId = locationId;
  }

  public PostReportRequestPayloadsInner meterPointId(
      @jakarta.annotation.Nonnull String meterPointId) {

    this.meterPointId = meterPointId;
    return this;
  }

  /**
   * Get meterPointId
   *
   * @return meterPointId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_METER_POINT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMeterPointId() {
    return meterPointId;
  }

  @JsonProperty(value = JSON_PROPERTY_METER_POINT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMeterPointId(@jakarta.annotation.Nonnull String meterPointId) {
    this.meterPointId = meterPointId;
  }

  public PostReportRequestPayloadsInner points(
      @jakarta.annotation.Nullable List<EnergyCurvePoint> points) {

    this.points = points;
    return this;
  }

  public PostReportRequestPayloadsInner addPointsItem(EnergyCurvePoint pointsItem) {
    if (this.points == null) {
      this.points = new ArrayList<>();
    }
    this.points.add(pointsItem);
    return this;
  }

  /**
   * Get points
   *
   * @return points
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<EnergyCurvePoint> getPoints() {
    return points;
  }

  @JsonProperty(value = JSON_PROPERTY_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPoints(@jakarta.annotation.Nullable List<EnergyCurvePoint> points) {
    this.points = points;
  }

  public PostReportRequestPayloadsInner resolution(@jakarta.annotation.Nonnull String resolution) {

    this.resolution = resolution;
    return this;
  }

  /**
   * Get resolution
   *
   * @return resolution
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESOLUTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getResolution() {
    return resolution;
  }

  @JsonProperty(value = JSON_PROPERTY_RESOLUTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResolution(@jakarta.annotation.Nonnull String resolution) {
    this.resolution = resolution;
  }

  public PostReportRequestPayloadsInner curvePoints(
      @jakarta.annotation.Nullable List<EnergyCurvePoint> curvePoints) {
    this.curvePoints = JsonNullable.<List<EnergyCurvePoint>>of(curvePoints);

    return this;
  }

  public PostReportRequestPayloadsInner addCurvePointsItem(EnergyCurvePoint curvePointsItem) {
    if (this.curvePoints == null || !this.curvePoints.isPresent()) {
      this.curvePoints = JsonNullable.<List<EnergyCurvePoint>>of(new ArrayList<>());
    }
    try {
      this.curvePoints.get().add(curvePointsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get curvePoints
   *
   * @return curvePoints
   * @deprecated
   */
  @Deprecated
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<EnergyCurvePoint> getCurvePoints() {
    return curvePoints.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CURVE_POINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public JsonNullable<List<EnergyCurvePoint>> getCurvePoints_JsonNullable() {
    return curvePoints;
  }

  @JsonProperty(JSON_PROPERTY_CURVE_POINTS)
  public void setCurvePoints_JsonNullable(JsonNullable<List<EnergyCurvePoint>> curvePoints) {
    this.curvePoints = curvePoints;
  }

  public void setCurvePoints(@jakarta.annotation.Nullable List<EnergyCurvePoint> curvePoints) {
    this.curvePoints = JsonNullable.<List<EnergyCurvePoint>>of(curvePoints);
  }

  public PostReportRequestPayloadsInner acknowledgedTargets(
      @jakarta.annotation.Nullable List<LPCLocation> acknowledgedTargets) {

    this.acknowledgedTargets = acknowledgedTargets;
    return this;
  }

  public PostReportRequestPayloadsInner addAcknowledgedTargetsItem(
      LPCLocation acknowledgedTargetsItem) {
    if (this.acknowledgedTargets == null) {
      this.acknowledgedTargets = new ArrayList<>();
    }
    this.acknowledgedTargets.add(acknowledgedTargetsItem);
    return this;
  }

  /**
   * Get acknowledgedTargets
   *
   * @return acknowledgedTargets
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACKNOWLEDGED_TARGETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LPCLocation> getAcknowledgedTargets() {
    return acknowledgedTargets;
  }

  @JsonProperty(value = JSON_PROPERTY_ACKNOWLEDGED_TARGETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcknowledgedTargets(
      @jakarta.annotation.Nullable List<LPCLocation> acknowledgedTargets) {
    this.acknowledgedTargets = acknowledgedTargets;
  }

  public PostReportRequestPayloadsInner declinedTargets(
      @jakarta.annotation.Nullable List<LPCLocation> declinedTargets) {

    this.declinedTargets = declinedTargets;
    return this;
  }

  public PostReportRequestPayloadsInner addDeclinedTargetsItem(LPCLocation declinedTargetsItem) {
    if (this.declinedTargets == null) {
      this.declinedTargets = new ArrayList<>();
    }
    this.declinedTargets.add(declinedTargetsItem);
    return this;
  }

  /**
   * Get declinedTargets
   *
   * @return declinedTargets
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DECLINED_TARGETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LPCLocation> getDeclinedTargets() {
    return declinedTargets;
  }

  @JsonProperty(value = JSON_PROPERTY_DECLINED_TARGETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeclinedTargets(@jakarta.annotation.Nullable List<LPCLocation> declinedTargets) {
    this.declinedTargets = declinedTargets;
  }

  public PostReportRequestPayloadsInner baseline(
      @jakarta.annotation.Nonnull List<EnergyCurvePoint> baseline) {

    this.baseline = baseline;
    return this;
  }

  public PostReportRequestPayloadsInner addBaselineItem(EnergyCurvePoint baselineItem) {
    if (this.baseline == null) {
      this.baseline = new ArrayList<>();
    }
    this.baseline.add(baselineItem);
    return this;
  }

  /**
   * Get baseline
   *
   * @return baseline
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BASELINE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<EnergyCurvePoint> getBaseline() {
    return baseline;
  }

  @JsonProperty(value = JSON_PROPERTY_BASELINE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBaseline(@jakarta.annotation.Nonnull List<EnergyCurvePoint> baseline) {
    this.baseline = baseline;
  }

  public PostReportRequestPayloadsInner flexibility(
      @jakarta.annotation.Nonnull List<EnergyCurvePoint> flexibility) {

    this.flexibility = flexibility;
    return this;
  }

  public PostReportRequestPayloadsInner addFlexibilityItem(EnergyCurvePoint flexibilityItem) {
    if (this.flexibility == null) {
      this.flexibility = new ArrayList<>();
    }
    this.flexibility.add(flexibilityItem);
    return this;
  }

  /**
   * Get flexibility
   *
   * @return flexibility
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FLEXIBILITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<EnergyCurvePoint> getFlexibility() {
    return flexibility;
  }

  @JsonProperty(value = JSON_PROPERTY_FLEXIBILITY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFlexibility(@jakarta.annotation.Nonnull List<EnergyCurvePoint> flexibility) {
    this.flexibility = flexibility;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostReportRequestPayloadsInner postReportRequestPayloadsInner =
        (PostReportRequestPayloadsInner) o;
    return Objects.equals(this.payloadType, postReportRequestPayloadsInner.payloadType)
        && Objects.equals(this.resourceId, postReportRequestPayloadsInner.resourceId)
        && Objects.equals(this.locationId, postReportRequestPayloadsInner.locationId)
        && Objects.equals(this.meterPointId, postReportRequestPayloadsInner.meterPointId)
        && Objects.equals(this.points, postReportRequestPayloadsInner.points)
        && Objects.equals(this.resolution, postReportRequestPayloadsInner.resolution)
        && equalsNullable(this.curvePoints, postReportRequestPayloadsInner.curvePoints)
        && Objects.equals(
            this.acknowledgedTargets, postReportRequestPayloadsInner.acknowledgedTargets)
        && Objects.equals(this.declinedTargets, postReportRequestPayloadsInner.declinedTargets)
        && Objects.equals(this.baseline, postReportRequestPayloadsInner.baseline)
        && Objects.equals(this.flexibility, postReportRequestPayloadsInner.flexibility);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b
        || (a != null
            && b != null
            && a.isPresent()
            && b.isPresent()
            && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        payloadType,
        resourceId,
        locationId,
        meterPointId,
        points,
        resolution,
        hashCodeNullable(curvePoints),
        acknowledgedTargets,
        declinedTargets,
        baseline,
        flexibility);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[] {a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostReportRequestPayloadsInner {\n");
    sb.append("    payloadType: ").append(toIndentedString(payloadType)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    locationId: ").append(toIndentedString(locationId)).append("\n");
    sb.append("    meterPointId: ").append(toIndentedString(meterPointId)).append("\n");
    sb.append("    points: ").append(toIndentedString(points)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("    curvePoints: ").append(toIndentedString(curvePoints)).append("\n");
    sb.append("    acknowledgedTargets: ")
        .append(toIndentedString(acknowledgedTargets))
        .append("\n");
    sb.append("    declinedTargets: ").append(toIndentedString(declinedTargets)).append("\n");
    sb.append("    baseline: ").append(toIndentedString(baseline)).append("\n");
    sb.append("    flexibility: ").append(toIndentedString(flexibility)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
