/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import java.util.Objects;

/** Problem */
@JsonPropertyOrder({Problem.JSON_PROPERTY_PROBLEM_TYPE, Problem.JSON_PROPERTY_MESSAGE})
@jakarta.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.12.0")
public class Problem {
  public static final String JSON_PROPERTY_PROBLEM_TYPE = "problemType";
  @jakarta.annotation.Nullable private ProblemType problemType;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull private String message;

  public Problem() {}

  public Problem problemType(@jakarta.annotation.Nullable ProblemType problemType) {

    this.problemType = problemType;
    return this;
  }

  /**
   * Get problemType
   *
   * @return problemType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROBLEM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ProblemType getProblemType() {
    return problemType;
  }

  @JsonProperty(JSON_PROPERTY_PROBLEM_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProblemType(@jakarta.annotation.Nullable ProblemType problemType) {
    this.problemType = problemType;
  }

  public Problem message(@jakarta.annotation.Nonnull String message) {

    this.message = message;
    return this;
  }

  /**
   * Get message
   *
   * @return message
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }

  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Problem problem = (Problem) o;
    return Objects.equals(this.problemType, problem.problemType)
        && Objects.equals(this.message, problem.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(problemType, message);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Problem {\n");
    sb.append("    problemType: ").append(toIndentedString(problemType)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
