/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Gets or Sets SparkEventPayloadType */
public enum SparkEventPayloadType {
  UNKNOWN("Unknown"),

  USER_ELIGIBILITY("UserEligibility"),

  PRICE_CURVE("PriceCurve"),

  LOCATION_LPC("LocationLPC"),

  RESOURCE_LPC("ResourceLPC"),

  LPC_RESERVATION("LPCReservation");

  private String value;

  SparkEventPayloadType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SparkEventPayloadType fromValue(String value) {
    for (SparkEventPayloadType b : SparkEventPayloadType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
