/*
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.voluespark.energycoordination.client.model;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/** Gets or Sets SparkReportPayloadType */
public enum SparkReportPayloadType {
  ENERGY_USAGE("EnergyUsage"),

  LOCATION_ENERGY_USAGE("LocationEnergyUsage"),

  RESOURCE_LPC_ACKNOWLEDGEMENT("ResourceLPCAcknowledgement"),

  LOCATION_LPC_ACKNOWLEDGEMENT("LocationLPCAcknowledgement");

  private String value;

  SparkReportPayloadType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SparkReportPayloadType fromValue(String value) {
    for (SparkReportPayloadType b : SparkReportPayloadType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
