inputSpec: https://api.sandbox.voluespark.com/energy-coordination/v1/swagger/Partner/swagger.json
generatorName: typescript-fetch
validateSpec: false
enablePostProcessFile: false
outputDir: .
additionalProperties:
  npmName: spark-ec-client
  supportsES6: true
  licenseName: MIT
