/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// GetEventsResponse
    /// </summary>
    [DataContract(Name = "GetEventsResponse")]
    public partial class GetEventsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventsResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetEventsResponse() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetEventsResponse" /> class.
        /// </summary>
        /// <param name="pagination">pagination (required).</param>
        /// <param name="events">events.</param>
        public GetEventsResponse(
            ApiPagination pagination = default(ApiPagination),
            List<GetEventResponse> events = default(List<GetEventResponse>)
        )
        {
            // to ensure "pagination" is required (not null)
            if (pagination == null)
            {
                throw new ArgumentNullException(
                    "pagination is a required property for GetEventsResponse and cannot be null"
                );
            }
            this.Pagination = pagination;
            this.Events = events;
        }

        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [DataMember(Name = "pagination", IsRequired = true, EmitDefaultValue = true)]
        public ApiPagination Pagination { get; set; }

        /// <summary>
        /// Gets or Sets Events
        /// </summary>
        [DataMember(Name = "events", EmitDefaultValue = false)]
        public List<GetEventResponse> Events { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetEventsResponse {\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("  Events: ").Append(Events).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(
                this,
                Newtonsoft.Json.Formatting.Indented
            );
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            yield break;
        }
    }
}
