/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// GetWebhookNotificationLogByIdResponse
    /// </summary>
    [DataContract(Name = "GetWebhookNotificationLogByIdResponse")]
    public partial class GetWebhookNotificationLogByIdResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWebhookNotificationLogByIdResponse" /> class.
        /// </summary>
        /// <param name="webhookNotificationLog">webhookNotificationLog.</param>
        /// <param name="notificationContent">notificationContent.</param>
        public GetWebhookNotificationLogByIdResponse(
            WebhookNotificationLog webhookNotificationLog = default,
            string notificationContent = default
        )
        {
            this.WebhookNotificationLog = webhookNotificationLog;
            this.NotificationContent = notificationContent;
        }

        /// <summary>
        /// Gets or Sets WebhookNotificationLog
        /// </summary>
        [DataMember(Name = "webhookNotificationLog", EmitDefaultValue = false)]
        public WebhookNotificationLog WebhookNotificationLog { get; set; }

        /// <summary>
        /// Gets or Sets NotificationContent
        /// </summary>
        [DataMember(Name = "notificationContent", EmitDefaultValue = false)]
        public string NotificationContent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWebhookNotificationLogByIdResponse {\n");
            sb.Append("  WebhookNotificationLog: ").Append(WebhookNotificationLog).Append("\n");
            sb.Append("  NotificationContent: ").Append(NotificationContent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(
                this,
                Newtonsoft.Json.Formatting.Indented
            );
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            yield break;
        }
    }
}
