/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// LPCDataPoint
    /// </summary>
    [DataContract(Name = "LPCDataPoint")]
    public partial class LPCDataPoint : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LPCDataPoint" /> class.
        /// </summary>
        /// <param name="maxPowerInKiloWatts">maxPowerInKiloWatts.</param>
        /// <param name="timestamp">timestamp.</param>
        public LPCDataPoint(
            double maxPowerInKiloWatts = default,
            DateTimeOffset timestamp = default
        )
        {
            this.MaxPowerInKiloWatts = maxPowerInKiloWatts;
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// Gets or Sets MaxPowerInKiloWatts
        /// </summary>
        [DataMember(Name = "maxPowerInKiloWatts", EmitDefaultValue = false)]
        public double MaxPowerInKiloWatts { get; set; }

        /// <summary>
        /// Gets or Sets Timestamp
        /// </summary>
        [DataMember(Name = "timestamp", EmitDefaultValue = false)]
        public DateTimeOffset Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LPCDataPoint {\n");
            sb.Append("  MaxPowerInKiloWatts: ").Append(MaxPowerInKiloWatts).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(
                this,
                Newtonsoft.Json.Formatting.Indented
            );
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            yield break;
        }
    }
}
