/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// Defines PriceArea
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PriceArea
    {
        /// <summary>
        /// Enum Unknown for value: Unknown
        /// </summary>
        [EnumMember(Value = "Unknown")]
        Unknown,

        /// <summary>
        /// Enum NO1 for value: NO1
        /// </summary>
        [EnumMember(Value = "NO1")]
        NO1,

        /// <summary>
        /// Enum NO2 for value: NO2
        /// </summary>
        [EnumMember(Value = "NO2")]
        NO2,

        /// <summary>
        /// Enum NO3 for value: NO3
        /// </summary>
        [EnumMember(Value = "NO3")]
        NO3,

        /// <summary>
        /// Enum NO4 for value: NO4
        /// </summary>
        [EnumMember(Value = "NO4")]
        NO4,

        /// <summary>
        /// Enum NO5 for value: NO5
        /// </summary>
        [EnumMember(Value = "NO5")]
        NO5,

        /// <summary>
        /// Enum FI for value: FI
        /// </summary>
        [EnumMember(Value = "FI")]
        FI,

        /// <summary>
        /// Enum DK1 for value: DK1
        /// </summary>
        [EnumMember(Value = "DK1")]
        DK1,

        /// <summary>
        /// Enum DK2 for value: DK2
        /// </summary>
        [EnumMember(Value = "DK2")]
        DK2,

        /// <summary>
        /// Enum SE1 for value: SE1
        /// </summary>
        [EnumMember(Value = "SE1")]
        SE1,

        /// <summary>
        /// Enum SE2 for value: SE2
        /// </summary>
        [EnumMember(Value = "SE2")]
        SE2,

        /// <summary>
        /// Enum SE3 for value: SE3
        /// </summary>
        [EnumMember(Value = "SE3")]
        SE3,

        /// <summary>
        /// Enum SE4 for value: SE4
        /// </summary>
        [EnumMember(Value = "SE4")]
        SE4,
    }
}
