/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// Defines ProblemType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ProblemType
    {
        /// <summary>
        /// Enum MissingMpidOnLocation for value: MissingMpidOnLocation
        /// </summary>
        [EnumMember(Value = "MissingMpidOnLocation")]
        MissingMpidOnLocation = 1,

        /// <summary>
        /// Enum CompensationMpidDoesNotMatchLocation for value: CompensationMpidDoesNotMatchLocation
        /// </summary>
        [EnumMember(Value = "CompensationMpidDoesNotMatchLocation")]
        CompensationMpidDoesNotMatchLocation = 2,
    }
}
