/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// ResourceLPCTarget
    /// </summary>
    [DataContract(Name = "ResourceLPCTarget")]
    public partial class ResourceLPCTarget : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceLPCTarget" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ResourceLPCTarget() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceLPCTarget" /> class.
        /// </summary>
        /// <param name="meterPointId">meterPointId (required).</param>
        /// <param name="locationId">locationId (required).</param>
        /// <param name="resourceId">resourceId (required).</param>
        /// <param name="resolution">resolution (required).</param>
        /// <param name="points">points (required).</param>
        public ResourceLPCTarget(
            string meterPointId = default,
            string locationId = default,
            string resourceId = default,
            string resolution = default,
            List<LPCDataPoint> points = default
        )
        {
            // to ensure "meterPointId" is required (not null)
            if (meterPointId == null)
            {
                throw new ArgumentNullException(
                    "meterPointId is a required property for ResourceLPCTarget and cannot be null"
                );
            }
            this.MeterPointId = meterPointId;
            // to ensure "locationId" is required (not null)
            if (locationId == null)
            {
                throw new ArgumentNullException(
                    "locationId is a required property for ResourceLPCTarget and cannot be null"
                );
            }
            this.LocationId = locationId;
            // to ensure "resourceId" is required (not null)
            if (resourceId == null)
            {
                throw new ArgumentNullException(
                    "resourceId is a required property for ResourceLPCTarget and cannot be null"
                );
            }
            this.ResourceId = resourceId;
            // to ensure "resolution" is required (not null)
            if (resolution == null)
            {
                throw new ArgumentNullException(
                    "resolution is a required property for ResourceLPCTarget and cannot be null"
                );
            }
            this.Resolution = resolution;
            // to ensure "points" is required (not null)
            if (points == null)
            {
                throw new ArgumentNullException(
                    "points is a required property for ResourceLPCTarget and cannot be null"
                );
            }
            this.Points = points;
        }

        /// <summary>
        /// Gets or Sets MeterPointId
        /// </summary>
        [DataMember(Name = "meterPointId", IsRequired = true, EmitDefaultValue = true)]
        public string MeterPointId { get; set; }

        /// <summary>
        /// Gets or Sets LocationId
        /// </summary>
        [DataMember(Name = "locationId", IsRequired = true, EmitDefaultValue = true)]
        public string LocationId { get; set; }

        /// <summary>
        /// Gets or Sets ResourceId
        /// </summary>
        [DataMember(Name = "resourceId", IsRequired = true, EmitDefaultValue = true)]
        public string ResourceId { get; set; }

        /// <summary>
        /// Gets or Sets Resolution
        /// </summary>
        /*
        <example>02:00:00</example>
        */
        [DataMember(Name = "resolution", IsRequired = true, EmitDefaultValue = true)]
        public string Resolution { get; set; }

        /// <summary>
        /// Gets or Sets Points
        /// </summary>
        [DataMember(Name = "points", IsRequired = true, EmitDefaultValue = true)]
        public List<LPCDataPoint> Points { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ResourceLPCTarget {\n");
            sb.Append("  MeterPointId: ").Append(MeterPointId).Append("\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  ResourceId: ").Append(ResourceId).Append("\n");
            sb.Append("  Resolution: ").Append(Resolution).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(
                this,
                Newtonsoft.Json.Formatting.Indented
            );
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            yield break;
        }
    }
}
