/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using JsonSubTypes;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// UserEligibilityPayload
    /// </summary>
    [DataContract(Name = "UserEligibilityPayload")]
    [JsonConverter(typeof(JsonSubtypes), "PayloadType")]
    public partial class UserEligibilityPayload : SparkEventPayload, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserEligibilityPayload" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserEligibilityPayload() { }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserEligibilityPayload" /> class.
        /// </summary>
        /// <param name="lastUpdated">lastUpdated (required).</param>
        /// <param name="addedUsers">addedUsers (required).</param>
        /// <param name="removedUsers">removedUsers (required).</param>
        /// <param name="payloadType">payloadType (required) (default to SparkEventPayloadType.UserEligibility).</param>
        public UserEligibilityPayload(
            DateTimeOffset lastUpdated = default(DateTimeOffset),
            List<string> addedUsers = default(List<string>),
            List<string> removedUsers = default(List<string>),
            SparkEventPayloadType payloadType = SparkEventPayloadType.UserEligibility
        )
            : base(payloadType)
        {
            this.LastUpdated = lastUpdated;
            // to ensure "addedUsers" is required (not null)
            if (addedUsers == null)
            {
                throw new ArgumentNullException(
                    "addedUsers is a required property for UserEligibilityPayload and cannot be null"
                );
            }
            this.AddedUsers = addedUsers;
            // to ensure "removedUsers" is required (not null)
            if (removedUsers == null)
            {
                throw new ArgumentNullException(
                    "removedUsers is a required property for UserEligibilityPayload and cannot be null"
                );
            }
            this.RemovedUsers = removedUsers;
        }

        /// <summary>
        /// Gets or Sets LastUpdated
        /// </summary>
        [DataMember(Name = "lastUpdated", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset LastUpdated { get; set; }

        /// <summary>
        /// Gets or Sets AddedUsers
        /// </summary>
        [DataMember(Name = "addedUsers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> AddedUsers { get; set; }

        /// <summary>
        /// Gets or Sets RemovedUsers
        /// </summary>
        [DataMember(Name = "removedUsers", IsRequired = true, EmitDefaultValue = true)]
        public List<string> RemovedUsers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserEligibilityPayload {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  LastUpdated: ").Append(LastUpdated).Append("\n");
            sb.Append("  AddedUsers: ").Append(AddedUsers).Append("\n");
            sb.Append("  RemovedUsers: ").Append(RemovedUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(
                this,
                Newtonsoft.Json.Formatting.Indented
            );
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(
            ValidationContext validationContext
        )
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }
}
