/*
 * Energy Coordination API - Partner Endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = EnergyCoordinationClient.Client.OpenAPIDateConverter;

namespace EnergyCoordinationClient.Model
{
    /// <summary>
    /// Defines WebhookStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WebhookStatus
    {
        /// <summary>
        /// Enum New for value: New
        /// </summary>
        [EnumMember(Value = "New")]
        New = 1,

        /// <summary>
        /// Enum Healthy for value: Healthy
        /// </summary>
        [EnumMember(Value = "Healthy")]
        Healthy = 2,

        /// <summary>
        /// Enum Unhealthy for value: Unhealthy
        /// </summary>
        [EnumMember(Value = "Unhealthy")]
        Unhealthy = 3,

        /// <summary>
        /// Enum TimeOut for value: TimeOut
        /// </summary>
        [EnumMember(Value = "TimeOut")]
        TimeOut = 4,
    }
}
