/* tslint:disable */
/* eslint-disable */
/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LPCReservationPayload } from './LPCReservationPayload';
import {
    instanceOfLPCReservationPayload,
    LPCReservationPayloadFromJSON,
    LPCReservationPayloadFromJSONTyped,
    LPCReservationPayloadToJSON,
} from './LPCReservationPayload';
import type { LocationLPCPayload } from './LocationLPCPayload';
import {
    instanceOfLocationLPCPayload,
    LocationLPCPayloadFromJSON,
    LocationLPCPayloadFromJSONTyped,
    LocationLPCPayloadToJSON,
} from './LocationLPCPayload';
import type { PriceCurvePayload } from './PriceCurvePayload';
import {
    instanceOfPriceCurvePayload,
    PriceCurvePayloadFromJSON,
    PriceCurvePayloadFromJSONTyped,
    PriceCurvePayloadToJSON,
} from './PriceCurvePayload';
import type { ResourceLPCPayload } from './ResourceLPCPayload';
import {
    instanceOfResourceLPCPayload,
    ResourceLPCPayloadFromJSON,
    ResourceLPCPayloadFromJSONTyped,
    ResourceLPCPayloadToJSON,
} from './ResourceLPCPayload';
import type { UserEligibilityPayload } from './UserEligibilityPayload';
import {
    instanceOfUserEligibilityPayload,
    UserEligibilityPayloadFromJSON,
    UserEligibilityPayloadFromJSONTyped,
    UserEligibilityPayloadToJSON,
} from './UserEligibilityPayload';

/**
 * @type GetEventResponsePayload
 * 
 * @export
 */
export type GetEventResponsePayload = LPCReservationPayload | LocationLPCPayload | PriceCurvePayload | ResourceLPCPayload | UserEligibilityPayload;

export function GetEventResponsePayloadFromJSON(json: any): GetEventResponsePayload {
    return GetEventResponsePayloadFromJSONTyped(json, false);
}

export function GetEventResponsePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEventResponsePayload {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfLPCReservationPayload(json)) {
        return LPCReservationPayloadFromJSONTyped(json, true);
    }
    if (instanceOfLocationLPCPayload(json)) {
        return LocationLPCPayloadFromJSONTyped(json, true);
    }
    if (instanceOfPriceCurvePayload(json)) {
        return PriceCurvePayloadFromJSONTyped(json, true);
    }
    if (instanceOfResourceLPCPayload(json)) {
        return ResourceLPCPayloadFromJSONTyped(json, true);
    }
    if (instanceOfUserEligibilityPayload(json)) {
        return UserEligibilityPayloadFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GetEventResponsePayloadToJSON(json: any): any {
    return GetEventResponsePayloadToJSONTyped(json, false);
}

export function GetEventResponsePayloadToJSONTyped(value?: GetEventResponsePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfLPCReservationPayload(value)) {
        return LPCReservationPayloadToJSON(value as LPCReservationPayload);
    }
    if (instanceOfLocationLPCPayload(value)) {
        return LocationLPCPayloadToJSON(value as LocationLPCPayload);
    }
    if (instanceOfPriceCurvePayload(value)) {
        return PriceCurvePayloadToJSON(value as PriceCurvePayload);
    }
    if (instanceOfResourceLPCPayload(value)) {
        return ResourceLPCPayloadToJSON(value as ResourceLPCPayload);
    }
    if (instanceOfUserEligibilityPayload(value)) {
        return UserEligibilityPayloadToJSON(value as UserEligibilityPayload);
    }
    return {};
}

