/* tslint:disable */
/* eslint-disable */
/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUserEnrollmentResponse
 */
export interface GetUserEnrollmentResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetUserEnrollmentResponse
     */
    readonly isEnrolled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetUserEnrollmentResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof GetUserEnrollmentResponse
     */
    enrollmentId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetUserEnrollmentResponse
     */
    enrollmentDate?: Date | null;
}

/**
 * Check if a given object implements the GetUserEnrollmentResponse interface.
 */
export function instanceOfGetUserEnrollmentResponse(value: object): value is GetUserEnrollmentResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function GetUserEnrollmentResponseFromJSON(json: any): GetUserEnrollmentResponse {
    return GetUserEnrollmentResponseFromJSONTyped(json, false);
}

export function GetUserEnrollmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserEnrollmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isEnrolled': json['isEnrolled'] == null ? undefined : json['isEnrolled'],
        'userId': json['userId'],
        'enrollmentId': json['enrollmentId'] == null ? undefined : json['enrollmentId'],
        'enrollmentDate': json['enrollmentDate'] == null ? undefined : (new Date(json['enrollmentDate'])),
    };
}

export function GetUserEnrollmentResponseToJSON(json: any): GetUserEnrollmentResponse {
    return GetUserEnrollmentResponseToJSONTyped(json, false);
}

export function GetUserEnrollmentResponseToJSONTyped(value?: Omit<GetUserEnrollmentResponse, 'isEnrolled'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'enrollmentId': value['enrollmentId'],
        'enrollmentDate': value['enrollmentDate'] == null ? undefined : ((value['enrollmentDate'] as any).toISOString()),
    };
}

