/* tslint:disable */
/* eslint-disable */
/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostUserRequest
 */
export interface PostUserRequest {
    /**
     * 
     * @type {string}
     * @memberof PostUserRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the PostUserRequest interface.
 */
export function instanceOfPostUserRequest(value: object): value is PostUserRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function PostUserRequestFromJSON(json: any): PostUserRequest {
    return PostUserRequestFromJSONTyped(json, false);
}

export function PostUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function PostUserRequestToJSON(json: any): PostUserRequest {
    return PostUserRequestToJSONTyped(json, false);
}

export function PostUserRequestToJSONTyped(value?: PostUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

