/* tslint:disable */
/* eslint-disable */
/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceArea } from './PriceArea';
import {
    PriceAreaFromJSON,
    PriceAreaFromJSONTyped,
    PriceAreaToJSON,
    PriceAreaToJSONTyped,
} from './PriceArea';
import type { PriceCurve } from './PriceCurve';
import {
    PriceCurveFromJSON,
    PriceCurveFromJSONTyped,
    PriceCurveToJSON,
    PriceCurveToJSONTyped,
} from './PriceCurve';
import type { SparkEventPayload } from './SparkEventPayload';
import {
    SparkEventPayloadFromJSON,
    SparkEventPayloadFromJSONTyped,
    SparkEventPayloadToJSON,
    SparkEventPayloadToJSONTyped,
} from './SparkEventPayload';
import type { SparkEventPayloadType } from './SparkEventPayloadType';
import {
    SparkEventPayloadTypeFromJSON,
    SparkEventPayloadTypeFromJSONTyped,
    SparkEventPayloadTypeToJSON,
    SparkEventPayloadTypeToJSONTyped,
} from './SparkEventPayloadType';
import type { PriceCurveTarget } from './PriceCurveTarget';
import {
    PriceCurveTargetFromJSON,
    PriceCurveTargetFromJSONTyped,
    PriceCurveTargetToJSON,
    PriceCurveTargetToJSONTyped,
} from './PriceCurveTarget';

/**
 * 
 * @export
 * @interface PriceCurvePayload
 */
export interface PriceCurvePayload extends SparkEventPayload {
    /**
     * 
     * @type {Array<PriceCurveTarget>}
     * @memberof PriceCurvePayload
     */
    targets: Array<PriceCurveTarget>;
    /**
     * 
     * @type {PriceCurve}
     * @memberof PriceCurvePayload
     */
    priceCurveDelta: PriceCurve;
    /**
     * 
     * @type {PriceArea}
     * @memberof PriceCurvePayload
     */
    priceArea: PriceArea;
}



/**
 * Check if a given object implements the PriceCurvePayload interface.
 */
export function instanceOfPriceCurvePayload(value: object): value is PriceCurvePayload {
    if (!('targets' in value) || value['targets'] === undefined) return false;
    if (!('priceCurveDelta' in value) || value['priceCurveDelta'] === undefined) return false;
    if (!('priceArea' in value) || value['priceArea'] === undefined) return false;
    return true;
}

export function PriceCurvePayloadFromJSON(json: any): PriceCurvePayload {
    return PriceCurvePayloadFromJSONTyped(json, false);
}

export function PriceCurvePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceCurvePayload {
    if (json == null) {
        return json;
    }
    return {
        ...SparkEventPayloadFromJSONTyped(json, true),
        'targets': ((json['targets'] as Array<any>).map(PriceCurveTargetFromJSON)),
        'priceCurveDelta': PriceCurveFromJSON(json['priceCurveDelta']),
        'priceArea': PriceAreaFromJSON(json['priceArea']),
    };
}

export function PriceCurvePayloadToJSON(json: any): PriceCurvePayload {
    return PriceCurvePayloadToJSONTyped(json, false);
}

export function PriceCurvePayloadToJSONTyped(value?: PriceCurvePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...SparkEventPayloadToJSONTyped(value, true),
        'targets': ((value['targets'] as Array<any>).map(PriceCurveTargetToJSON)),
        'priceCurveDelta': PriceCurveToJSON(value['priceCurveDelta']),
        'priceArea': PriceAreaToJSON(value['priceArea']),
    };
}

