/* tslint:disable */
/* eslint-disable */
/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationType } from './NotificationType';
import {
    NotificationTypeFromJSON,
    NotificationTypeFromJSONTyped,
    NotificationTypeToJSON,
    NotificationTypeToJSONTyped,
} from './NotificationType';

/**
 * 
 * @export
 * @interface PutWebhookRequest
 */
export interface PutWebhookRequest {
    /**
     * 
     * @type {string}
     * @memberof PutWebhookRequest
     */
    webhookSecret?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PutWebhookRequest
     */
    webhookUrl: string;
    /**
     * 
     * @type {Array<NotificationType>}
     * @memberof PutWebhookRequest
     */
    notificationTypes?: Array<NotificationType>;
    /**
     * 
     * @type {boolean}
     * @memberof PutWebhookRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PutWebhookRequest
     */
    name?: string | null;
}

/**
 * Check if a given object implements the PutWebhookRequest interface.
 */
export function instanceOfPutWebhookRequest(value: object): value is PutWebhookRequest {
    if (!('webhookUrl' in value) || value['webhookUrl'] === undefined) return false;
    return true;
}

export function PutWebhookRequestFromJSON(json: any): PutWebhookRequest {
    return PutWebhookRequestFromJSONTyped(json, false);
}

export function PutWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'webhookSecret': json['webhookSecret'] == null ? undefined : json['webhookSecret'],
        'webhookUrl': json['webhookUrl'],
        'notificationTypes': json['notificationTypes'] == null ? undefined : ((json['notificationTypes'] as Array<any>).map(NotificationTypeFromJSON)),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PutWebhookRequestToJSON(json: any): PutWebhookRequest {
    return PutWebhookRequestToJSONTyped(json, false);
}

export function PutWebhookRequestToJSONTyped(value?: PutWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'webhookSecret': value['webhookSecret'],
        'webhookUrl': value['webhookUrl'],
        'notificationTypes': value['notificationTypes'] == null ? undefined : ((value['notificationTypes'] as Array<any>).map(NotificationTypeToJSON)),
        'enabled': value['enabled'],
        'name': value['name'],
    };
}

