/* tslint:disable */
/* eslint-disable */
/**
 * Energy Coordination API - Partner Endpoints
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetEventResponse } from './GetEventResponse';
import {
    GetEventResponseFromJSON,
    GetEventResponseFromJSONTyped,
    GetEventResponseToJSON,
    GetEventResponseToJSONTyped,
} from './GetEventResponse';

/**
 * 
 * @export
 * @interface SimulateEventResponse
 */
export interface SimulateEventResponse {
    /**
     * 
     * @type {GetEventResponse}
     * @memberof SimulateEventResponse
     */
    simulatedEvent?: GetEventResponse;
}

/**
 * Check if a given object implements the SimulateEventResponse interface.
 */
export function instanceOfSimulateEventResponse(value: object): value is SimulateEventResponse {
    return true;
}

export function SimulateEventResponseFromJSON(json: any): SimulateEventResponse {
    return SimulateEventResponseFromJSONTyped(json, false);
}

export function SimulateEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulateEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'simulatedEvent': json['simulatedEvent'] == null ? undefined : GetEventResponseFromJSON(json['simulatedEvent']),
    };
}

export function SimulateEventResponseToJSON(json: any): SimulateEventResponse {
    return SimulateEventResponseToJSONTyped(json, false);
}

export function SimulateEventResponseToJSONTyped(value?: SimulateEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'simulatedEvent': GetEventResponseToJSON(value['simulatedEvent']),
    };
}

