name: OpenAPI codegen

on:
  schedule:
    - cron: "0 9 * * *" # Every day at 9AM
  workflow_dispatch:

jobs:
  compare-swagger:
    runs-on: ubuntu-latest
    outputs:
      checksums_match: ${{ steps.compare_checksums.outputs.match }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compare swagger.json checksums
        id: compare_checksums
        working-directory: ./_common
        run: |
          curl --retry 5 --retry-max-time 120 -o latest-ec-sandbox-swagger.json https://api.sandbox.voluespark.com/energy-coordination/v1/swagger/Partner/swagger.json
          remote_checksum=$(sha256sum latest-ec-sandbox-swagger.json | cut -d ' ' -f 1)
          local_checksum=$(sha256sum ec-sandbox-swagger.json | cut -d ' ' -f 1)
          match=$([ "$local_checksum" = "$remote_checksum" ] && echo true || echo false)
          echo "Checksums match: $match"
          echo "match=$match" >> "$GITHUB_OUTPUT"
          [ $match = "true" ] || mv latest-ec-sandbox-swagger.json ec-sandbox-swagger.json

      - name: Upload new swagger.json artifact
        uses: actions/upload-artifact@v4
        if: steps.compare_checksums.outputs.match == 'false'
        with:
          name: swagger-json
          path: ./*_common/ec-sandbox-swagger.json

  codegen:
    name: Codegen for ${{ matrix.config.language }} ${{ matrix.generator-type }}
    runs-on: ubuntu-latest
    needs: compare-swagger
    if: needs.compare-swagger.outputs.checksums_match == 'false'
    defaults:
      run:
        working-directory: ${{ matrix.config.language }}/${{ matrix.generator-type }}
    strategy:
      fail-fast: false
      matrix:
        generator-type:
          - client
          - server
        config:
          - language: csharp
            post-process-command: dotnet tool restore && dotnet csharpier src
          - language: java
            post-process-command: |
              mvn --ntp dependency:copy -Dartifact=com.google.googlejavaformat:google-java-format:LATEST:jar:all-deps -DoutputDirectory=.. -Dmdep.stripVersion
              java -jar ../google-java-format-all-deps.jar -i @.openapi-generator/FILES
          - language: typescript
        exclude:
          - config:
              language: typescript
            generator-type: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Needed to install and run openapi-generator-cli
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Setup .NET
        if: ${{ matrix.config.language == 'csharp' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.*"

      - name: Install openapi-generator-cli
        run: |
          mkdir -p ~/bin/openapitools
          curl --retry 5 --retry-max-time 120 -o ~/bin/openapitools/openapi-generator-cli https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh
          chmod u+x ~/bin/openapitools/openapi-generator-cli
          # This should be removed once the following PR is merged:
          # https://github.com/OpenAPITools/openapi-generator/pull/19614
          git clone https://github.com/OpenAPITools/openapi-generator --depth 1 ~/bin/openapitools/openapi-generator
          cd ~/bin/openapitools/openapi-generator
          git fetch origin pull/19614/head:pr-19614 --depth 1
          git checkout pr-19614
          mvn --ntp install -N
          mvn --ntp package -Dmaven.test.skip -Djacoco.skip -Dmdep.skip -pl modules/openapi-generator,modules/openapi-generator-cli,modules/openapi-generator-core
          cp modules/openapi-generator-cli/target/openapi-generator-cli.jar ~/bin/openapitools/openapi-generator-cli-pr19614.jar

      - name: Run code generation for ${{ matrix.config.language }} ${{ matrix.generator-type }}
        # This should be removed once the PR is merged
        env:
          OPENAPI_GENERATOR_VERSION: pr19614
        run: |
          # Remove old generated files
          cat .openapi-generator/FILES | xargs rm -f
          ~/bin/openapitools/openapi-generator-cli batch --fail-fast openapi-generator-config.yaml
          ${{ matrix.config.post-process-command }}
          echo "ARTIFACT_NAME=${{ matrix.config.language }}-${{ matrix.generator-type }}" >> $GITHUB_ENV

      - name: Test client
        if: ${{ matrix.generator-type == 'client' }}
        env:
          CLIENT_ID: ${{ secrets.SANDBOX_EC_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SANDBOX_EC_CLIENT_SECRET }}
        run: ../../_tests/cli-client-test.sh ${{ matrix.config.language }}

      - name: Test webhook server
        if: matrix.generator-type == 'server'
        run: ../../_tests/webhook-server-test.sh ${{ matrix.config.language }}

      - name: Upload generated code from ${{ matrix.config.language }} ${{ matrix.generator-type }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          include-hidden-files: true
          path: ./*${{ matrix.config.language }}/${{ matrix.generator-type }}
          if-no-files-found: error

  commit-changes:
    runs-on: ubuntu-latest
    needs: codegen
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all generated code
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          echo "The following files have changed:"
          git diff --staged
          git commit -m "Update swagger.json and autogenerated code"
          # git push
